Main Menu (WIP)
Albin-P/Fyrvalla-Jam pull request #6
Opened 2022-03-28 09:21 UTC by Persson03

Mestadels av menyn

2022-03-28 09:57 UTC, Albin-P requested changes
Du har merge conflicts. Se till att din develop är uppdaterad utan conflicts först.

2022-04-05 20:00 UTC, Albin-P approved these changes

2022-04-05 20:36 UTC, larsnordstrom commented
Du har strul i din kod som måste fixas för att det ska gå att lägga till i projektet. Du petar i för många saker i varje pullrequest....

2022-04-05 20:40 UTC, larsnordstrom commented
Du har commits i levels, menyer, animeringar....

2022-04-25 09:00 UTC, merged